config/routes.rb
Rails.application.routes.draw do

  resources :perfils
  resources :estados
  resources :tipos
  resources :fotos
  get 'solicitud/index'

  resources :departamentos
  resources :proyectos
  resources :usuarios
  root 'home#index'

  resources :proformas
  resources :cita 
  resources :cotizacions

  get 'home/proyecto'
  get 'cotizacions/index'
  #get 'proformas/index'
  #get 'index', controller: :proformas, action: :index, alias: 'index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	
	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	belongs_to :proyecto
	
	validates :proyecto_id , presence: true
	validates :nombre, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :area, numericality: true 
	validates :piso, numericality: true 
	validates :estado, length: { maximum: 150 }
	validates :tipo, length: { maximum: 150 } 
	
	
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/foto.rb
class Foto < ApplicationRecord

  mount_uploader :imagen, PictureUploader
  belongs_to :departamento
  belongs_to :proyecto
end

app/models/perfil.rb
class Perfil < ApplicationRecord

	has_many :usuario

end

app/models/proforma.rb
class Proforma < ApplicationRecord
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord

	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	has_many :departamento

	validates :nombre, length: { maximum: 150 }, presence: true
	validates :ubicacion, presence: true
	validates :preciobase, numericality: true, presence: true 

end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord

    belongs_to :perfil

	validates :dni , presence: true
	validates :nombres, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :apellidos, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :correo, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}

	validates :telefono, numericality: true , presence: true
	validates :perfil, length: { maximum: 150 }, presence: true

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]
  layout 'internal_administrador'
  # GET /proyectos
  # GET /proyectos.json
  def index
    pNombre = "%#{params[:nombre]}%" 
    @proyectos = Proyecto.paginate(page: params[:page], per_page:5).where("id !=0 and nombre like ?", pNombre.to_s)
    
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @fotos = @proyecto.fotos.all
    respond_to do |f|
      f.js
    end
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
    @foto = @proyecto.fotos.build

    respond_to do |f|
      f.js
    end
  end

  # GET /proyectos/1/edit
  def edit
    respond_to do |f|
      f.js
    end
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save

        params[:fotos]['imagen'].each do |a|
          @foto = @proyecto.fotos.create!( :imagen => a, :proyecto_id => @proyecto.id, :departamento_id => 0 )
        end   

        format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
        format.js   { render layout: false, content_type: 'text/javascript' }

        #format.html { flash.now[:alert] = "Not done" render "new" }
        #format.json { render json: {:errors => @proyecto.errors}, status: :unprocessable_entity }
        #format.js { render :js=>'alert("not done");' } 
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
        format.js   { render layout: false, content_type: 'text/javascript' }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @foto.destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      #params.require(:proyecto).permit(:id, :nombre, :ubicacion, :preciobase)
      params.require(:proyecto).permit(:id, :nombre, :ubicacion, :preciobase, fotos_attributes: [:id, :proyecto_id, :imagen]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/proformas_helper.rb
module ProformasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/solicitud_helper.rb
module SolicitudHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/proyectos/_edit.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-edit-Proyecto" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Proyecto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body --> 
       <%= form_for(@proyecto, html: { :multipart => true }, remote: true) do |form| %>
          <div class="modal-body">
          
          <% if @proyecto.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

              <ul>
              <% proyecto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field" hidden="true">
            <%= form.label :id %>
            <%= form.number_field :id %>
          </div>

          <div class="field">
            <%= form.label :nombre %>
            <%= form.text_field :nombre, {:class => "form-control", :placeholder => "Ingrese nombre"}  %>
          </div>

          <div class="field">
            <%= form.label :ubicacion, "Ubicación" %>
            <%= form.text_field :ubicacion,  {:class => "form-control", :placeholder => "Ingrese ubicación"}  %>
          </div>

          <div class="field">
            <%= form.label :preciobase, "Precio Base" %>
            <%= form.number_field :preciobase,  {:class => "form-control", :placeholder => "Ingrese Precio"}  %>
          </div>

          <%= form.fields_for :fotos do |p| %>
           <div class="field">
             <%= p.label :imagen %><br>
             <%= p.file_field :imagen, :multiple => true, name: "fotos[imagen][]" %>

           </div>
          <% end %>


       </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <%= form.submit "Guardar",  :class => "btn btn-primary", :onclick => "return ValidarProyecto()" %>
      </div>
 	
      <% end %>
    </div>
  </div>
</div>

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto, local: true) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :proyecto_id %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :proyecto_nombre %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion, id: :proyecto_ubicacion %>
  </div>

  <div class="field">
    <%= form.label :preciobase %>
    <%= form.text_field :preciobase, id: :proyecto_preciobase %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/_new.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-new-Proyecto" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Proyecto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body --> 
        <%= form_for(@proyecto, html: { :multipart => true }, remote: true) do |form| %>
          <div class="modal-body">
            <div id="error_messages"></div>
          <% if @proyecto.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

              <ul>
              <% proyecto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field" hidden="true">
            <%= form.label :id %>
            <%= form.number_field :id %>
          </div>

          <div class="field">
            <%= form.label :nombre %>
            <%= form.text_field :nombre, {:class => "form-control", :placeholder => "Ingrese nombre"}  %>
          </div>

          <div class="field">
            <%= form.label :ubicacion, "Ubicación" %>
            <%= form.text_field :ubicacion,  {:class => "form-control", :placeholder => "Ingrese ubicación"}  %>
          </div>

          <div class="field">
            <%= form.label :preciobase, "Precio Base" %>
            <%= form.number_field :preciobase,  {:class => "form-control", :placeholder => "Ingrese Precio"}  %>
          </div>

          <%= form.fields_for :fotos do |p| %>
           <div class="field">
             <%= p.label :imagen %><br>             
             <%= p.file_field :imagen,  :multiple => true, name: "fotos[imagen][]" %>
           </div>
          <% end %>


       </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
       <%= form.submit "Guardar",  :class => "btn btn-primary", :onclick => "return ValidarProyecto()" %>
       <!-- <%= form.submit "Guardar",  :class => "btn btn-primary", :onclick => "return ValidarProyecto()", data: {confirm: '¿Esta Seguro de Guardar?'} %> --> 

      </div>
 	
      <% end %>
    </div>
  </div>
</div>

app/views/proyectos/_show.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-show-Proyecto" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Proyecto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body --> 
       <div class="form-control">
      		
      		<p>
      		  <strong>Id:</strong>
      		  <%= @proyecto.id %>
      		</p>

      		<p>
      		  <strong>Nombre:</strong>
      		  <%= @proyecto.nombre %>
      		</p>

      		<p>
      		  <strong>Ubicacion:</strong>
      		  <%= @proyecto.ubicacion %>
      		</p>

      		<p>
      		  <strong>Precio Base:</strong>
      		  <%= @proyecto.preciobase %>
      		</p>

          <p>
            <strong>Imagen:</strong>
            <br/>
            <br/>
            <% @fotos.each do |p| %>
              <%= image_tag p.imagen_url, :width => 50 %>
              <%= link_to "Editar", edit_foto_path(p) %>
            <% end %>

          </p>

       </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
 	    
    </div>
  </div>
</div>

app/views/proyectos/edit.js.erb
$('#edit-Proyecto').html("<%= j (render 'edit' ) %>");
$('#Modal-edit-Proyecto').modal('show')

app/views/proyectos/index.html.erb
<h1>B&uacute;squeda de Proyectos</h1>

<%= form_tag proyectos_path, :method => 'get' do  %>

  <div class="col-12">

    <div class="row">        
      <div class="col-lg-3 col-md-3 col-sm-12 p-0 ">
        <div class="autocomplete"> 
          <%= text_field_tag  :nombre, params[:nombre], { :class => "form-control", :placeholder => "Proyecto"} %> 
        </div>
      </div>
    </div>

    <div class="row">
      <br>
    </div>

    <div class="row">   

<div class="col-lg-3 col-md-3 col-sm-12 p-0 ">    
    <%= link_to  new_proyecto_path,  :remote=> true  do %>
          <button  title="Nuevo" class="btn btn-primary">
            <i class="fa fa-plus-circle"> </i> Nuevo
          </button>              
        <% end %>     
                   
        <%= submit_tag "Buscar", :class => "btn btn-info" %>        
      </div>
    </div>

    

    <div class="row">
      <br>
    </div>

  
  </div>
<% end %>

<div class="table-responsive">
  <table  class="table" >
    <thead>
      <tr>
        <th>Item</th>
        <th>Nombre</th>
        <th>Ubicaci&oacute;n</th>
        <th>Precio base</th>                
        <th colspan="3">Acci&oacute;n</th>
      </tr>
    </thead>

    <tbody>
      <% @proyectos.each do |proyecto| %>
        <tr>
          <td><%= proyecto.id %></td>
          <td><%= proyecto.nombre %></td>
          <td><%= proyecto.ubicacion %></td>
          <td><%= proyecto.preciobase %></td>          
                    
           <td>
            <%= link_to proyecto,  :remote=>true  do %>
             <button type="button" class="btn btn-info" title="Ver">
                <i class="fas fa-search"></i>
              </button>            
            <% end %>
          </td>

          <td>
            <%= link_to edit_proyecto_path(proyecto),  :remote=>true  do %>
              <button type="button" class="btn btn-warning" title="Editar">
                <i class="fa fa-pencil-alt"></i> 
              </button>
            <% end %>
          </td>

          <td>
            <%= link_to proyecto, method: :delete, data: { confirm: '¿Estas seguro de eliminar?' }, :remote=>true  do %>
             <button type="button" class="btn btn-danger" title="Eliminar">
                <i class="fa fa-trash-alt"></i>
              </button>            
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation example">
     <%= will_paginate @proyectos, :class => 'pagination justify-content-center' %>
  </nav>

</div>
<br>


<!-- INI The Modal -->
<div id="new-Proyecto"> </div>
<div id="edit-Proyecto"> </div>
<div id="show-Proyecto"> </div>
<div id="error-Proyecto"> </div>

<!-- FIN The Modal -->

app/views/proyectos/new.js.erb
$('#new-Proyecto').html("<%= j (render 'new' ) %>");
$('#Modal-new-Proyecto').modal('show')
/*
$( function() {
   $("form[data-remote='true']").remoteValidation();
 });*/

app/views/proyectos/show.js.erb
$('#show-Proyecto').html("<%= j (render 'show' ) %>");
$('#Modal-show-Proyecto').modal('show')