config/routes.rb
Rails.application.routes.draw do

  resources :perfils
  resources :estados
  resources :tipos
  resources :fotos
  get 'solicitud/index'

  resources :departamentos
  resources :proyectos
  resources :usuarios
  root 'home#index'

  resources :proformas
  resources :cita 
  resources :cotizacions

  get 'home/proyecto'
  get 'cotizacions/index'
  #get 'proformas/index'
  #get 'index', controller: :proformas, action: :index, alias: 'index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	
	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	belongs_to :proyecto
	
	validates :proyecto_id , presence: true
	validates :nombre, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :area, numericality: true 
	validates :piso, numericality: true 
	validates :estado, length: { maximum: 150 }
	validates :tipo, length: { maximum: 150 } 
	
	
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/foto.rb
class Foto < ApplicationRecord

  mount_uploader :imagen, PictureUploader
  belongs_to :departamento
  belongs_to :proyecto
end

app/models/perfil.rb
class Perfil < ApplicationRecord

	has_many :usuario

end

app/models/proforma.rb
class Proforma < ApplicationRecord
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord

	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	has_many :departamento

	validates :nombre, length: { maximum: 150 }, presence: true
	validates :ubicacion, presence: true
	validates :preciobase, numericality: true, presence: true 

end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord

    belongs_to :perfil

	validates :dni , presence: true
	validates :nombres, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :apellidos, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :correo, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}

	validates :telefono, numericality: true , presence: true
	validates :perfil, length: { maximum: 150 }, presence: true

end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]
  layout 'internal_administrador'
  # GET /departamentos
  # GET /departamentos.json
  def index
    
    pNombre = "%#{params[:nombre]}%"  
    pEstado = "%#{params[:estado]}%"
    

    if params[:proyecto_id] == "0"
       pProyectoId = "%%" 
      puts "paso"
    else
       pProyectoId = "%#{params[:proyecto_id]}%" 
    end

    @departamentos = Departamento.paginate(page: params[:page], per_page:5).where("id !=0 and nombre like ? and proyecto_id like ? and estado like ?", pNombre.to_s, pProyectoId.to_s, pEstado.to_s)

    @proyectos = Proyecto.all 
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @fotos = @departamento.fotos.all

    respond_to do |f|
      f.js
    end
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
    @foto = @departamento.fotos.build

    respond_to do |f|
      f.js
    end
  end

  # GET /departamentos/1/edit
  def edit
    respond_to do |f|
      f.js
    end
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save

        params[:fotos]['imagen'].each do |a|
          @foto = @departamento.fotos.create!( :imagen => a, :proyecto_id => 0, :departamento_id =>@departamento.id )
        end  

        format.html { redirect_to departamentos_url, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
       
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
        format.js   { render layout: false, content_type: 'text/javascript' }
      end
    end

  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamentos_url, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
        format.js   { render layout: false, content_type: 'text/javascript' }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:id, :nombre, :area, :piso, :estado, :tipo, :proyecto_id, fotos_attributes: [:id, :departamento_id, :imagen])
      #params.require(:departamento).permit(:id, :proyectoId, :nombre, :area, :piso, :estado, :tipo, :proyecto_id)
    end
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/proformas_helper.rb
module ProformasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/solicitud_helper.rb
module SolicitudHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/departamentos/_edit.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-edit-Departamento" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Departamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body -->      
      <%= form_for @departamento, :remote=>true  do |form| %>
        <div class="modal-body">

          <% if @departamento.errors.any? %>
            <div id="card border-0">
             <!-- <div id="error_explanation">-->  
              <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

              <ul>
              <% departamento.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>


          <div class="field">
             <%= form.label :proyecto_id, "Proyecto" %>
             <%= form.select :proyecto_id, Proyecto.all.where("id !=0").collect {|e| [e.nombre, e.id] }, { :include_blank => "Seleccione" }, { :class => "form-control" } %>  
          </div>

          <div class="field">
            <%= form.label :nombre %>
            <%= form.text_field :nombre, {:class => "form-control", :placeholder => "Ingrese nombre"} %>
          </div>

          <div class="field">
            <%= form.label :area %>
            <%= form.number_field :area, {:class => "form-control", :placeholder => "Ingrese área"}  %>
          </div>

          <div class="field">
            <%= form.label :piso %> 
            <%= form.number_field :piso, {:class => "form-control", :placeholder => "Ingrese piso"}  %>
          </div>

          <div class="field">
             <%= form.label :tipo, "Tipo" %>
             <%= form.select :tipo, [["Residencial", 1], ["Ubanización", 2]], { :include_blank => "Seleccione" }, { :class => "form-control" } %>
          </div>

          <div class="field">
            <%= form.label :estado %>                       
             <%= form.select :estado, [["Disponible", 1], ["Separado", 2], ["Vendido", 3]], { :include_blank => "Seleccione" }, { :class => "form-control"} %>
          </div>
          
          <%= form.fields_for :fotos do |p| %>
           <div class="field">
             <%= p.label :imagen %><br>             
             <%= p.file_field :imagen,  :multiple => true, name: "fotos[imagen][]" %>
           </div>
          <% end %>

      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <%= form.submit "Guardar",  :class => "btn btn-primary", :onclick => "return ValidarDepartamento()" %>
      </div>


      <% end %>
    </div>
  </div>
</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :departamento_id %>
  </div>

  <div class="field">
    <%= form.label :proyectoId, "Seleccione Proyecto" %>
    <%= form.select :proyectoId, [["Condominio Chorrillos", 1], ["Condominio Surco", 2]], { :include_blank => "Seleccione" }, { :class => "form-control" } %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :departamento_nombre,{:class => "form-control", :placeholder => "Ingrese nombre"} %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area, id: :departamento_area %>
  </div>

  <div class="field">
    <%= form.label :piso %>
    <%= form.number_field :piso, id: :departamento_piso %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :departamento_estado %>
  </div>

  <div class="field">
    <%= form.label :tipo, "Seleccione Proyecto" %>
    <%= form.select :tipo, [["Residencial", 1], ["Ubanización", 2]], { :include_blank => "Seleccione" }, { :class => "form-control" } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/_new.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-new-Departamento" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Departamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body -->      
      <%= form_for @departamento, :remote=>true  do |form| %>
        <div class="modal-body">

          <% if @departamento.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

              <ul>
              <% departamento.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field" hidden="true" >
            <%= form.label :id %>
            <%= form.number_field :id %>
          </div>

          <div class="field">
             <%= form.label :proyecto_id, "Proyecto" %>
             <%= form.select :proyecto_id, Proyecto.all.where("id !=0").collect {|e| [e.nombre, e.id] }, { :include_blank => "Seleccione" }, { :class => "form-control" } %>  
          </div>

          <div class="field">
            <%= form.label :nombre %>
            <%= form.text_field :nombre, {:class => "form-control", :placeholder => "Ingrese nombre"} %>
          </div>

          <div class="field">
            <%= form.label :area %>
            <%= form.number_field :area, {:class => "form-control", :placeholder => "Ingrese área"}  %>
          </div>

          <div class="field">
            <%= form.label :piso %> 
            <%= form.number_field :piso, {:class => "form-control", :placeholder => "Ingrese piso"}  %>
          </div>

          <div class="field">
             <%= form.label :tipo, "Tipo" %>
             <%= form.select :tipo, [["Residencial", 1], ["Ubanización", 2]], { :include_blank => "Seleccione" }, { :class => "form-control" } %>
             
          </div>
      
          <div class="field">
            <%= form.label :estado %>
            <br/>
           
            <%= form.select :estado, [["Disponible", 1]], { :include_blank => false}, {:class => "form-control", :disabled => true} %>
             <!-- <%= form.select :estado, [["Disponible", 1], ["Separado", 2], ["Vendido", 3]], { :include_blank => "Seleccione" }, { :class => "form-control"} %>-->
          </div>

          <%= form.fields_for :fotos do |p| %>
           <div class="field">
             <%= p.label :imagen %><br>             
             <%= p.file_field :imagen,  :multiple => true, name: "fotos[imagen][]" %>
           </div>
          <% end %>


      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
       <%= form.submit "Guardar",  :class => "btn btn-primary", :onclick => "return ValidarDepartamento()" %>
      </div>


      <% end %>
    </div>
  </div>
</div>

app/views/departamentos/_show.html.erb
<!-- The Modal -->
<div class="modal fade" id="Modal-show-Departamento" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Departamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- Modal body -->      
       <div class="form-control">

        <p>
        <strong>Proyecto:</strong>
          <%= Proyecto.select(:nombre).where("id = " + @departamento.proyecto_id.to_s).collect(&:nombre)[0] %>  
        </p>
       
        <p>
        <strong>Nombre:</strong>
          <%= @departamento.nombre %>
        </p>

        <p>
        <strong>Area:</strong>
          <%= @departamento.area %>
        </p>

        <p>
        <strong>Piso:</strong>
          <%= @departamento.piso %>
        </p>

        <p>
        <strong>Estado:</strong>
          <%= Estado.select(:nombre).where("id = " + @departamento.estado.to_s).collect(&:nombre)[0] %>  
        </p>

        <p>
        <strong>Tipo:</strong>
          <%= Tipo.select(:nombre).where("id = " + @departamento.tipo.to_s).collect(&:nombre)[0] %>  
        </p>     

        <p>
            <strong>Imagen:</strong>
            <br/>
            <br/>
            <% @fotos.each do |p| %>
              <%= image_tag p.imagen_url, :width => 50 %>
              <%= link_to "Editar", edit_foto_path(p) %>
            <% end %>

          </p>     

      </div>

       <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>


      
    </div>
  </div>
</div>

app/views/departamentos/edit.js.erb
$('#edit-Departamento').html("<%= j (render 'edit' ) %>");
$('#Modal-edit-Departamento').modal('show')

app/views/departamentos/index.html.erb
<h1>B&uacute;squeda de Departamentos</h1>

 
<%= form_tag departamentos_path, :method => 'get' do  %>

  <div class="col-12">
    
    <div class="row">

        <div class="col-lg-3 col-md-3 col-sm-12 p-0 ">   
          <%= select_tag "proyecto_id", options_from_collection_for_select(@proyectos, "id", "nombre"), { :class => "form-control"} %>
        </div>  

        <div class="col-lg-3 col-md-3 col-sm-12 p-0">   
          <div class="autocomplete">        
            <%= text_field_tag :nombre, params[:nombre], { :class => "form-control", :placeholder => "Departamento"} %> 
          </div>  
        </div>    

        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
          <%= select_tag "estado", options_for_select({"Estado" => "", "Disponible" => "1", "Separado" => "2" , "Vendido" => "3" }), { :class => "form-control"} %>
        </div>  

    </div>
    <br>

    <div class="row">
      <div class="col-lg-9 col-md-9 col-sm-12 p-0">  
          <%= link_to  new_departamento_path,  :remote=>true  do %>
            <button  title="Nuevo" class="btn btn-primary">
              <i class="fa fa-plus-circle"> </i> Nuevo
            </button>              
          <% end %>

          <%= submit_tag  "Buscar", :class => "btn btn-info" %>            
      </div> 
    </div>
    <br>



  </div>
<% end %>

<div class="table-responsive">
  <table  class="table" >
    <thead>
      <tr>
       
        <th>Proyecto</th>
        <th>Departamento</th>
        <th>Area</th>  
        <th>Piso</th>   
        <th>Tipo</th>
             
        <th>Estado</th>      
        <th colspan="3">Acci&oacute;n</th>
      </tr>
    </thead>

    <tbody>
      <% @departamentos.each do |departamento| %>
        <tr>
         
          <td>
             <%= Proyecto.select(:nombre).where("id = " + departamento.proyecto_id.to_s).collect(&:nombre)[0]  %>
          </td>
          
          <td><%= departamento.nombre %></td>
          <td><%= departamento.area %></td>
          <td><%= departamento.piso %></td>
          <td>
            <%= Tipo.select(:nombre).where("id = " + departamento.tipo.to_s).collect(&:nombre)[0]  %>
          </td>

          <td>
            <%= Estado.select(:nombre).where("id = " + departamento.estado.to_s).collect(&:nombre)[0]  %>
          </td>
          
          
          <td>
            <%= link_to  departamento,  :remote=>true  do %>
             <button  type="button" class="btn btn-info" 
              title="Ver">
               <i class="fas fa-search"></i>
              </button>            
            <% end %>
          </td>

          <td>
            <%= link_to edit_departamento_path(departamento),  :remote=>true  do %>
              <button type="button" class="btn btn-warning" title="Editar">
                <i class="fa fa-pencil-alt"></i> 
              </button>
            <% end %>
          </td>

          <td>
            <%= link_to departamento,  method: :delete, data: { confirm: '¿Estas seguro de eliminar?' }, :remote=>true  do %>
             <button  type="button" class="btn btn-danger" title="Eliminar">
                <i class="fa fa-trash-alt"></i>
              </button>            
            <% end %>
          </td>

        </tr>
        <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation example">
     <%= will_paginate @departamentos, :class => 'pagination justify-content-center' %>
  </nav>


</div>
<br>

<!-- INI The Modal -->
<div id="new-Departamento"> </div>
<div id="edit-Departamento"> </div>
<div id="show-Departamento"> </div>
<!-- FIN The Modal -->

 

app/views/departamentos/new.js.erb
$('#new-Departamento').html("<%= j (render 'new' ) %>");
$('#Modal-new-Departamento').modal('show')

app/views/departamentos/show.js.erb
$('#show-Departamento').html("<%= j (render 'show' ) %>");
$('#Modal-show-Departamento').modal('show')