config/routes.rb
Rails.application.routes.draw do

  resources :perfils
  resources :estados
  resources :tipos
  resources :fotos
  get 'solicitud/index'

  resources :departamentos
  resources :proyectos
  resources :usuarios
  root 'home#index'

  resources :proformas
  resources :cita 
  resources :cotizacions

  get 'home/proyecto'
  get 'cotizacions/index'
  #get 'proformas/index'
  #get 'index', controller: :proformas, action: :index, alias: 'index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	
	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	belongs_to :proyecto
	
	validates :proyecto_id , presence: true
	validates :nombre, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :area, numericality: true 
	validates :piso, numericality: true 
	validates :estado, length: { maximum: 150 }
	validates :tipo, length: { maximum: 150 } 
	
	
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/foto.rb
class Foto < ApplicationRecord

  mount_uploader :imagen, PictureUploader
  belongs_to :departamento
  belongs_to :proyecto
end

app/models/perfil.rb
class Perfil < ApplicationRecord

	has_many :usuario

end

app/models/proforma.rb
class Proforma < ApplicationRecord
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord

	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	has_many :departamento

	validates :nombre, length: { maximum: 150 }, presence: true
	validates :ubicacion, presence: true
	validates :preciobase, numericality: true, presence: true 

end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord

    belongs_to :perfil

	validates :dni , presence: true
	validates :nombres, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :apellidos, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :correo, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}

	validates :telefono, numericality: true , presence: true
	validates :perfil, length: { maximum: 150 }, presence: true

end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/proformas_helper.rb
module ProformasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/solicitud_helper.rb
module SolicitudHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :estado_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.nombre %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estado.nombre %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>