config/routes.rb
Rails.application.routes.draw do

  resources :perfils
  resources :estados
  resources :tipos
  resources :fotos
  get 'solicitud/index'

  resources :departamentos
  resources :proyectos
  resources :usuarios
  root 'home#index'

  resources :proformas
  resources :cita 
  resources :cotizacions

  get 'home/proyecto'
  get 'cotizacions/index'
  #get 'proformas/index'
  #get 'index', controller: :proformas, action: :index, alias: 'index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/citum.rb
class Citum < ApplicationRecord
end

app/models/cotizacion.rb
class Cotizacion < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	
	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	belongs_to :proyecto
	
	validates :proyecto_id , presence: true
	validates :nombre, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :area, numericality: true 
	validates :piso, numericality: true 
	validates :estado, length: { maximum: 150 }
	validates :tipo, length: { maximum: 150 } 
	
	
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/foto.rb
class Foto < ApplicationRecord

  mount_uploader :imagen, PictureUploader
  belongs_to :departamento
  belongs_to :proyecto
end

app/models/perfil.rb
class Perfil < ApplicationRecord

	has_many :usuario

end

app/models/proforma.rb
class Proforma < ApplicationRecord
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord

	#Implementacion de imagenes
	has_many :fotos
	accepts_nested_attributes_for :fotos
	
	has_many :departamento

	validates :nombre, length: { maximum: 150 }, presence: true
	validates :ubicacion, presence: true
	validates :preciobase, numericality: true, presence: true 

end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord

    belongs_to :perfil

	validates :dni , presence: true
	validates :nombres, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :apellidos, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}
	validates :correo, length: { maximum: 150 } , presence: {
		message: "es obligatorio"
	}

	validates :telefono, numericality: true , presence: true
	validates :perfil, length: { maximum: 150 }, presence: true

end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/proformas_helper.rb
module ProformasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/solicitud_helper.rb
module SolicitudHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
  <section id="footer">
    <div class="container">
      <!--
      <div class="row text-center text-xs-center text-sm-left text-md-left">
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Quick links</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
         
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          
        </div>
      </div>
    
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
          </ul>
        </div>
        </hr>
      </div> 
      --> 
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p><u><a href="https://www.upc.edu.pe/">J&J Corp.</a></u> Prolongación Primavera 2390, Monterrico, Santiago de Surco 
Informes: 313-3333 - 610-5030 | Servicio al alumno 630-3333 | Fax: 313-3334 
Contacto | Política de Privacidad | Términos y Condiciones</p>
          <p class="h6">&copy Todos los derechos reservados.<a class="text-green ml-2" href="https://www.upc.edu.pe" target="_blank">J&J Corp.</a></p>
        </div>
        </hr>
      </div>  
    </div>
  </section>
<!-- ./Footer -->

app/views/layouts/_menu_administrador.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
  <ul class="navbar-nav nav-flex-icons ">      
      <li class="nav-item avatar">
       <a class="navbar-brand" href="#">
    <img src="https://botw-pd.s3.amazonaws.com/styles/logo-thumbnail/s3/062013/logo-jj.png?itok=JbTKnCcI" height="100" alt="Logo">
  </a>      
      </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item active">
      <%= link_to  'Usuarios', usuarios_path, {:class => "nav-link navbar-brand"} %>
    </li>
    <li class="nav-item">
      <%= link_to  'Proyectos', proyectos_path, {:class => "nav-link navbar-brand"} %>
    </li>
    <li class="nav-item">
      <%= link_to  'Departamentos', departamentos_path, {:class => "nav-link navbar-brand"} %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto nav-flex-icons">      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"  data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-7.jpg" class="rounded-circle z-depth-0"
            alt="Avatar image">
        </a>
        <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary">
          <a class="dropdown-item" href="#">Salir</a>
        </div>
      </li>
  </ul>
</nav>

app/views/layouts/_menu_asesor.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
  <ul class="navbar-nav nav-flex-icons ">      
      <li class="nav-item avatar">
       <a class="navbar-brand" href="#">
    <img src="https://botw-pd.s3.amazonaws.com/styles/logo-thumbnail/s3/062013/logo-jj.png?itok=JbTKnCcI" height="100" alt="Logo">
  </a>      
      </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item active">      
      <%= link_to 'Cotización', cotizacions_path, {:class => "nav-link navbar-brand"} %> 
    </li>
    <li class="nav-item active">
      <%= link_to  'Citas', cita_path, {:class => "nav-link navbar-brand"} %>
    </li>
    <li class="nav-item active">
      <%= link_to 'Proforma', proformas_path, {:class => "nav-link navbar-brand"} %>      
    </li>
  </ul>
  <ul class="navbar-nav ml-auto nav-flex-icons">      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"  data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-7.jpg" class="rounded-circle z-depth-0"
            alt="Avatar image">
        </a>
        <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary">         
          <a class="dropdown-item" href="#">Salir</a>
        </div>
      </li>
  </ul>
</nav>

app/views/layouts/_menu_inicio.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark sticky-top">
  <ul class="navbar-nav nav-flex-icons ">      
      <li class="nav-item avatar">
       <a class="navbar-brand" href="#">
    <img src="https://botw-pd.s3.amazonaws.com/styles/logo-thumbnail/s3/062013/logo-jj.png?itok=JbTKnCcI" height="100" alt="Logo">
  </a>      
      </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item active">      
     <a class="nav-link navbar-brand" href="#">Nosotros</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link navbar-brand" href="#">Cont&aacute;ctanos</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto nav-flex-icons">      
      <li class="nav-item">
        <%= link_to 'Iniciar sesión', cotizacions_path, {:class => "btn btn-warning wrn-btn"} %>         
      </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>J&J Corp.</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

     
    
  </head>

  <body>
    <%= render 'layouts/menu_inicio' %>  
  	<div class="container">
  		<%= yield %>
  	</div> 
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/layouts/internal_administrador.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <title>Tf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

     <script type="text/javascript" src="javascripts/remote_validation.js"></script>

    <style type="text/css">
  /* Footer */
  section {
      padding: 60px 0;
  }

  section .section-title {
      text-align: center;
      color: #007b5e;
      margin-bottom: 50px;
      text-transform: uppercase;
  }
  #footer {
      background: #007b5e !important;
  }
  #footer h5{
    padding-left: 10px;
      border-left: 3px solid #eeeeee;
      padding-bottom: 6px;
      margin-bottom: 20px;
      color:#ffffff;
  }
  #footer a {
      color: #ffffff;
      text-decoration: none !important;
      background-color: transparent;
      -webkit-text-decoration-skip: objects;
  }
  #footer ul.social li{
    padding: 3px 0;
  }
  #footer ul.social li a i {
      margin-right: 5px;
    font-size:25px;
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
  }
  #footer ul.social li:hover a i {
    font-size:30px;
    margin-top:-10px;
  }
  #footer ul.social li a,
  #footer ul.quick-links li a{
    color:#ffffff;
  }
  #footer ul.social li a:hover{
    color:#eeeeee;
  }
  #footer ul.quick-links li{
    padding: 3px 0;
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
  }
  #footer ul.quick-links li:hover{
    padding: 3px 0;
    margin-left:5px;
    font-weight:700;
  }
  #footer ul.quick-links li a i{
    margin-right: 5px;
  }
  #footer ul.quick-links li:hover a i {
      font-weight: 700;
  }

  @media (max-width:767px){
    #footer h5 {
      padding-left: 0;
      border-left: transparent;
      padding-bottom: 0px;
      margin-bottom: 10px;
    }
  }
</style>
  </head>

  <body>
  
    <%= render 'layouts/menu_administrador' %>  
   
    <main>    
      <div class="container">
     
          <%= yield :intro %>
          <%= yield %>
        
      </div>
   </main>
     <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/internal_asesor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <title>Tf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style type="text/css">
  /* Footer */
  section {
      padding: 60px 0;
  }

  section .section-title {
      text-align: center;
      color: #007b5e;
      margin-bottom: 50px;
      text-transform: uppercase;
  }
  #footer {
      background: #007b5e !important;
  }
  #footer h5{
    padding-left: 10px;
      border-left: 3px solid #eeeeee;
      padding-bottom: 6px;
      margin-bottom: 20px;
      color:#ffffff;
  }
  #footer a {
      color: #ffffff;
      text-decoration: none !important;
      background-color: transparent;
      -webkit-text-decoration-skip: objects;
  }
  #footer ul.social li{
    padding: 3px 0;
  }
  #footer ul.social li a i {
      margin-right: 5px;
    font-size:25px;
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
  }
  #footer ul.social li:hover a i {
    font-size:30px;
    margin-top:-10px;
  }
  #footer ul.social li a,
  #footer ul.quick-links li a{
    color:#ffffff;
  }
  #footer ul.social li a:hover{
    color:#eeeeee;
  }
  #footer ul.quick-links li{
    padding: 3px 0;
    -webkit-transition: .5s all ease;
    -moz-transition: .5s all ease;
    transition: .5s all ease;
  }
  #footer ul.quick-links li:hover{
    padding: 3px 0;
    margin-left:5px;
    font-weight:700;
  }
  #footer ul.quick-links li a i{
    margin-right: 5px;
  }
  #footer ul.quick-links li:hover a i {
      font-weight: 700;
  }

  @media (max-width:767px){
    #footer h5 {
      padding-left: 0;
      border-left: transparent;
      padding-bottom: 0px;
      margin-bottom: 10px;
    }
  }
</style>

  </head>

  <body>
   
      <%= render 'layouts/menu_asesor' %>  
   
    <main>    
    	<div class="container">
     
          <%= yield :intro %>
      		<%= yield %>
        
    	</div>
   </main>
     <%= render 'layouts/footer' %>
  </body>
</html>